[ec2]
3.253.244.137 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/terraform_ec2
#[local]
#192.168.1.27  ansible_user=ansible ansible_password=582200 ansible_become_password=582200 ansible_ssh_private_key_file=~/.ssh/terraform_ec2
